# Generated by Django 4.2.13 on 2024-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bank",
            name="code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
