# Generated by Django 4.2.13 on 2024-06-22 07:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0002_user_account_name_user_account_number_user_bank_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="expire_at",
            field=models.DateTimeField(default=account.models.generatedTime),
        ),
    ]
