# Generated by Django 4.2.13 on 2024-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
