# Generated by Django 4.2.13 on 2024-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0007_permission_rolepermission_roles_delete_permissions_and_more",
        ),
        ("account", "0002_bank_active_bank_code_bank_country_bank_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(to="beaverly_api.roles"),
        ),
    ]
