# Generated by Django 4.2.13 on 2024-07-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_pins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pins",
            name="customer",
        ),
        migrations.AddField(
            model_name="pins",
            name="email",
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pins",
            name="pin",
            field=models.TextField(db_index=True),
        ),
    ]
