# Generated by Django 4.2.13 on 2025-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_pins_customer_pins_email_alter_pins_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('password_reset', 'password_reset'), ('transaction', 'transaction'), ('verification', 'verification')], max_length=20),
        ),
    ]
