# version: '3.8'
services:
#web service app
  app:
    build: 
      context: .
    image: beaverly_backend 
    container_name: beaverly_backend_container
    #mount
    volumes:
      - ./:/app
      - media_volume:/app/mediafiles/
      - static_volume:/app/staticfiles/
    expose:
      - 8000
    command: sh -c "python manage.py makemigrations 
              && python manage.py migrate 
              && python manage.py collectstatic --noinput
              && gunicorn beaverly_app.wsgi:application -b 0.0.0.0:8000"
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db

  # celery:
  #   build: .
  #   image: celery_app
  #   container_name: celery_container
  #   volumes:
  #     - ./:/app
  #   command: "celery -A djangotest worker --loglevel=INFO"
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SECRET_KEY=${SECRET_KEY}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - CELERY_BROKER=${CELERY_BROKER}
  #     - CELERY_BACKEND=${CELERY_BACKEND}

  #   depends_on:
  #     - redis
  #     - app
    
volumes:
  # redis_data:
  # postgres_data:
  static_volume:
  media_volume:



    

    