# Generated by Django 4.2.13 on 2024-06-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beaverly_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapyBoostBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("NG", "NG"), ("USD", "USD")],
                        default="NG",
                        max_length=10,
                    ),
                ),
                ("expire_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capyboost_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
