# Generated by Django 4.2.13 on 2024-06-25 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0002_capyboostbalance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capyboostbalance",
            old_name="balance",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="capyboostbalance",
            name="deposit_percentage",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="capyboostbalance",
            name="inital_deposit",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="capyboostbalance",
            name="pay_off_amount",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="capyboostbalance",
            name="repayment_schedule",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="capyboostbalance",
            name="transaction_fee",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="capysafeaccount",
            name="pay_off_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
