# Generated by Django 4.2.13 on 2024-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0002_withdrawals_transactionhistory_smartproaccount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingwithdrawals",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
