# Generated by Django 4.2.13 on 2024-06-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0003_alter_pendingwithdrawals_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="recepit",
            new_name="receipt",
        ),
    ]
