# Generated by Django 4.2.13 on 2024-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0003_rename_balance_capyboostbalance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capyboostbalance",
            name="account_status",
            field=models.CharField(
                choices=[("pending", "pending"), ("paid", "paid")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
