# Generated by Django 4.2.13 on 2024-06-23 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0004_rename_recepit_transactionhistory_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="deposit_percentage",
            field=models.FloatField(
                default=0.1,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="expire_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="inital_deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="leaverage_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="pay_off_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="transaction_fee",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("top_up", "Top_up"),
                    ("leaverage", "Leaverage"),
                    ("sell_portfolio", "Sell_Portfolio"),
                    ("transfer", "Transfer"),
                ],
                default="deposit",
                max_length=30,
            ),
        ),
    ]
