# Generated by Django 4.2.13 on 2024-06-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0004_alter_capyboostbalance_account_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capyboostbalance",
            old_name="account_status",
            new_name="loan_status",
        ),
    ]
