# Generated by Django 4.2.13 on 2024-06-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0005_rename_account_status_capyboostbalance_loan_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capyboostbalance",
            name="amount",
        ),
    ]
