# Generated by Django 4.2.13 on 2024-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0005_transactionhistory_deposit_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="account_type",
            field=models.CharField(
                choices=[("low_risk", "Low_risk"), ("smart_pro", "Smart_pro")],
                default="low_risk",
                max_length=30,
            ),
        ),
    ]
