# Generated by Django 4.2.13 on 2024-06-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0006_remove_capyboostbalance_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capyboostbalance",
            name="loan_status",
        ),
    ]
