# Generated by Django 4.2.13 on 2024-06-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0007_permission_rolepermission_roles_delete_permissions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="description",
        ),
    ]
