# Generated by Django 4.2.13 on 2024-06-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0007_remove_capyboostbalance_loan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="capyboostbalance",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
