# Generated by Django 4.2.13 on 2024-06-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0008_remove_roles_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="description",
        ),
    ]
