# Generated by Django 4.2.13 on 2024-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0009_rename_pay_off_amount_capyboostbalance_loan_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="capyboostbalance",
            name="remaining_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
