# Generated by Django 4.2.13 on 2024-06-24 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beaverly_api", "0009_remove_permission_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SmartProAccount",
            new_name="CapyMaxAccount",
        ),
        migrations.RenameModel(
            old_name="LowRiskAccount",
            new_name="CapySafeAccount",
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="account_type",
            field=models.CharField(
                choices=[("CapySafe", "CapySafe"), ("CapyMax", "CapyMax")],
                default="CapySafe",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("top_up", "Top_up"),
                    ("capyboost", "capyboost"),
                    ("sell_portfolio", "Sell_Portfolio"),
                    ("transfer", "Transfer"),
                ],
                default="deposit",
                max_length=30,
            ),
        ),
    ]
