# Generated by Django 4.2.13 on 2024-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0010_capyboostbalance_remaining_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycdocumentimage",
            name="has_verified",
        ),
        migrations.RemoveField(
            model_name="kycselfie",
            name="has_verified",
        ),
        migrations.RemoveField(
            model_name="kycutilitybills",
            name="has_verified",
        ),
        migrations.RemoveField(
            model_name="livephotokyc",
            name="has_verified",
        ),
        migrations.AddField(
            model_name="kycdocumentimage",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "verified")],
            ),
        ),
        migrations.AddField(
            model_name="kycselfie",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "verified")],
            ),
        ),
        migrations.AddField(
            model_name="kycutilitybills",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "verified")],
            ),
        ),
        migrations.AddField(
            model_name="livephotokyc",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "verified")],
            ),
        ),
    ]
