# Generated by Django 4.2.13 on 2024-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0011_remove_kycdocumentimage_has_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocumentimage",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "unverified")],
            ),
        ),
        migrations.AlterField(
            model_name="kycselfie",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "unverified")],
            ),
        ),
        migrations.AlterField(
            model_name="kycutilitybills",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "unverified")],
            ),
        ),
        migrations.AlterField(
            model_name="livephotokyc",
            name="status",
            field=models.CharField(
                default="unverified",
                max_length=10,
                verbose_name=[("verified", "verified"), ("unverified", "unverified")],
            ),
        ),
    ]
