# Generated by Django 4.2.13 on 2024-06-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0012_alter_kycdocumentimage_status_alter_kycselfie_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="capyboostbalance",
            old_name="remaining_balance",
            new_name="payoff_amount",
        ),
    ]
