# Generated by Django 4.2.13 on 2024-06-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_api",
            "0013_rename_remaining_balance_capyboostbalance_payoff_amount",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capyboostbalance",
            name="loan_amount",
        ),
    ]
