# Generated by Django 4.2.13 on 2024-07-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_api", "0014_remove_capyboostbalance_loan_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capysafeaccount",
            name="pay_off_amount",
        ),
    ]
