# Generated by Django 4.2.13 on 2024-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capysafeaccount",
            name="customer",
        ),
        migrations.DeleteModel(
            name="CapyMaxAccount",
        ),
        migrations.DeleteModel(
            name="CapySafeAccount",
        ),
    ]
