# Generated by Django 4.2.13 on 2024-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0002_remove_capysafeaccount_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("contract_duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("repayment_duration", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="contract_duration",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="repayment_schedule",
        ),
    ]
