# Generated by Django 4.2.13 on 2024-06-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0003_contractduration_repaymentschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="contract_duration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beaverly_payment.contractduration",
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="repayment_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beaverly_payment.repaymentschedule",
            ),
        ),
    ]
