# Generated by Django 4.2.13 on 2024-06-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0004_transactionhistory_contract_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="contract_duration",
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="repayment_schedule",
        ),
    ]
