# Generated by Django 4.2.13 on 2024-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_payment",
            "0005_remove_transactionhistory_contract_duration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="contract_duration",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="repayment_schedule",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
