# Generated by Django 4.2.13 on 2024-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0006_transactionhistory_contract_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repaymentschedule",
            name="transaction_fee",
            field=models.FloatField(null=True),
        ),
    ]
