# Generated by Django 4.2.13 on 2024-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0007_repaymentschedule_transaction_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="amount_repaid",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
