# Generated by Django 4.2.13 on 2024-06-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0008_transactionhistory_amount_repaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="credited_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
