# Generated by Django 4.2.13 on 2024-06-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0009_transactionhistory_credited_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="account_type",
            field=models.CharField(
                choices=[("CapySafe", "CapySafe"), ("CapyMax", "CapyMax")],
                max_length=30,
                null=True,
            ),
        ),
    ]
