# Generated by Django 4.2.13 on 2024-06-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beaverly_payment", "0010_alter_transactionhistory_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
