# Generated by Django 4.2.13 on 2024-06-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0011_transactionhistory_received_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="amount_repaid",
        ),
    ]
