# Generated by Django 4.2.13 on 2024-06-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0012_remove_transactionhistory_amount_repaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="bank_details",
            field=models.JSONField(null=True),
        ),
    ]
