# Generated by Django 4.2.13 on 2024-07-01 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0013_transactionhistory_bank_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="deposit_percentage",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
