# Generated by Django 4.2.13 on 2024-07-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beaverly_payment", "0014_alter_transactionhistory_deposit_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="credited_amount",
            new_name="amount_charged",
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="amount_repaid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="amount_settled",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
