# Generated by Django 4.2.13 on 2024-07-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "beaverly_payment",
            "0015_rename_credited_amount_transactionhistory_amount_charged_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="amount_charged",
        ),
    ]
